### ISSUE TITLE
indigo branch depends on changes only present in bwi_common fern/led_study branch

### ISSUE THREAD

**Issue by rdelfin** [utexas-bwi/segbot#108]
In the Indigo branch, file `segbot_led/src/led_control_server.cpp` includes `bwi_msgs/LEDCameraStatus.h`, which is only present in `bwi_common`'s `fern/led_study`. This breaks a clean clone of a new bwi clean install. Either `fern/led_study` needs to be merged into indigo or the changes that caused this dependency need to be moved out into a separate branch or repo.

I have not tested this issue in the `kinetic` branch, so I am unsure if the changes are there too.
@FernandezR

**Comment by rdelfin** [comment]
I tried working on `fern/led_study` on both `bwi_common` and `segbot`, but a separate issue shows up with  `bwi_services/SpeakMessage.h`. As a temporary solution I went back to the `indigo` branches and deleted `segbot_led` locally. It seems to have fixed the issue, but we need a better solution.

**Comment by FernandezR** [comment]
The main branch of indigo should be updated though it seems that it is not. I'll try to do a pull request with the changes.

**Comment by FernandezR** [comment]
You should be fine now with the indigo branch, I made pull request and merged it.
