### ISSUE TITLE
segbot_bringup: not installing udev rules

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/segbot#26]
add a script to do the install

**Comment by piyushk** [comment]
We can automatically install udev rules. See https://groups.google.com/forum/#!topic/ros-sig-buildsystem/JqQjpcitobM

This means that the script should only be used when testing a source install, and correct udev rules are not already installed in the system deb. In any case, we should not be installing the script that install udev rules, as we don't want it accidentally run via a deb install.

I will use this issue to track this problem. Assigning to self.

**Comment by jack-oquin** [comment]
I wonder now if we actually want to install the rules on every machine.

Maybe only the robots?

**Comment by piyushk** [comment]
That's an excellent point. I didn't realize that those rules would affect every machine our code was installed on. Let's stick with the script for now. I'll close this issue since I've verified that the script is getting installed with the current release.
