### ISSUE TITLE
kinect in segbot_sensors

### ISSUE THREAD

**Issue by mleonetti** [utexas-bwi/segbot#37]
the new kinect.launch in segbot_sensors includes  file="$(find freenect_launch)/launch/freenect_tf_prefix.launch which apparently doesn't exist, at least on Roberto. Do we need to update something?

**Comment by piyushk** [comment]
You'll need to download the hydro-devel branch from freenect_stack while the new deb is being built.

https://github.com/ros-drivers/freenect_stack/tree/hydro-devel
```
wstool set freenect_stack --git https://github.com/ros-drivers/freenect_stack.git --version-new hydro-devel
wstool update freenect_stack
```
