### ISSUE TITLE
segbot_sensors: smooth voltage data in battery diagnostics node

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/segbot#39]
The raw battery voltages reported seem to fluctuate by several tenths of a volt. We decided to go ahead and publish the raw readings on the ``/battery0`` topic, but for reporting purposes it seems better to smooth out the data. 

A reasonable approach is for **battery_diagnostics** to apply an [exponentially weighted moving average](http://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average) to the sequence of voltage readings.

Let ``alpha`` be the weighting parameter between 0 and 1. It could be a ROS parameter with default around 0.25. In the [voltageCallback()](https://github.com/utexas-bwi/segbot/blob/master/segbot_sensors/src/segbot_sensors/battery_diagnostics.cpp#L19) set ``voltage`` to the initial reading, then apply this recursive update with each subsequent message:
```c++
voltage = alpha * msg->voltage + (1.0 - alpha) * voltage;
```
@maxsvetlik: does that look OK?

**Comment by maxsvetlik** [comment]
Looks good to me
