### ISSUE TITLE
segbot_bringup: segbot_v2.arm.launch missing in master

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/segbot#47]
This causes the bwi launch file checks to fail:

 * http://jenkins.ros.org/job/devel-indigo-bwi/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/5/testReport/(root)/Results/test_ran/

The referenced file exists in the ``piyushk/0.3.3`` branch. I don't know if that is safe to merge into ``master`` yet.

**Comment by piyushk** [comment]
Closed via cbd00b20e46b38c472a22b10a9331fabfc790. The launch file has been moved to the segbot_arm_launch package in the segbot_arm repo.
