### ISSUE TITLE
segbot_logical_translator: rename package and move to bwi_common?

### ISSUE THREAD

**Issue by piyushk** [utexas-bwi/segbot#54]
Issue migrated from redundant segbot_apps repository. 

@jack-oquin Original report

As far as I can tell, this package has nothing specifically to do with the segbot platform. It only depends on bwi_common packages and other low-level components, like multi_level_map.

Perhaps I am missing some reason why it needs to be segbot-specific?

At any rate, this can be delayed until the end of the semester, if that seems advisable.

**Comment by maxsvetlik** [comment]
Reposted issue #96 fixed this. Closing.
