### ISSUE TITLE
libbwi_mapper undefined symbol prevents segbot launch

### ISSUE THREAD

**Issue by maxsvetlik** [utexas-bwi/segbot#66]
On a fresh workspace, and a fresh install of the codebase, I'm seeing the following error when running the standard 
$ roslaunch bwi_launch segbot_v2.launch
on clamps (a v2):

/home/users/max/catkin_ws_update/devel/lib/segbot_logical_translator/segbot_logical_navigator: symbol lookup error: /home/users/max/catkin_ws_update/devel/lib/libbwi_mapper.so: undefined symbol: _ZN10map_server15loadMapFromFileEPN8nav_msgs15GetMapResponse_ISaIvEEEPKcdbddPdb

and subsequently 

[segbot_logical_navigator-9] process has died ...

which prevents the global and local costmaps from receiving the map.

If I checkout  39e6a0b, everything works correctly and I'm able to launch a robot. So the commits in question are 0bcaad6 and 1c85ba8. 
@FernandezR

**Comment by FernandezR** [comment]
After creating a fresh workspace the error was not reproduced and did not occur again for Max.
