### ISSUE TITLE
Travis CI: fix failures

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/segbot#98]
The solution will probably be similar to what was done for utexas-bwi/bwi_common#102

**Comment by jack-oquin** [comment]
The Kinetic build failed with the following error:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by jack-oquin** [comment]
Not sure what the cause of the timeout problem is. There are an awful lot of packages being built for Kinetic. It would be nice if more of the dependencies could be released as binaries.

**Comment by jack-oquin** [comment]
The fact that the Indigo tests are working is encouraging. They require fewer source repositories to build.

**Comment by jack-oquin** [comment]
I attempted a suggested work-around for Travis jobs timing out, but it did not work with the ROS-I tools.

see: https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out

**Comment by jack-oquin** [comment]
I have not made any progress in solving the Travis timeout with the Kinetic branch. Things I've tried:

 * [Using travis_wait to increase the timeout](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out)
 * [Running the CI job locally](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#run-industrial-ci-on-local-host) (both ways)

**Comment by 130s** [comment]
I know this is a dumb thing to ask, but do builds on 1) local computer 2) if possible on Docker (since with industrial_ci each job runs on Docker) pass and/or leave any hints?

If you're curious if this is industrial_ci related I recommend opening a ticket there (I'm a maintainer. We'll like to hear users' issues).

**Comment by jack-oquin** [comment]
Isaac! Good to hear from you. I really admire your excellent work on **industrial_ci**.

I have no reason to believe our current problems are in **industrial_ci**. I did run tests on my local computer using both **run_ci** and **run_travis** (I believe those are with and without docker), but so far have not succeeded. I no longer have the shell output from those attempts. In one case, package dependencies included within the workspace were not getting resolved by rosdep. I probably did not configure my workspace correctly for that, somehow.

I suspect that the root cause of our difficulty on Kinetic is too many repositories and packages being built in a single Travis job, because we are still building several repo dependencies that have not been released to ROS Kinetic. Our Indigo branch tests are all working fine.

Also, one of our dependencies is a CMake library package, [libsegwayrmp](https://github.com/utexas-bwi/libsegwayrmp), which is not catkin, although it does have a ``package.xml``. We build it from source using catkin tools, but maybe it's a problem for **industrial_ci**? Your docs say only catkin packages are supported.

I am thinking of ways to break the tests up into more manageable chunks, maybe creating our own PPA for some packages we can't release into the ROS repositories. That would be worthwhile, even if some other problem turns out to be at work here.

**Comment by jack-oquin** [comment]
Just building our whole code base on Kinetic is badly bogging down one of the old segbot_v2 laptops.

We need to create methods like using catkin tools whitelists that make it easy to compile only a useful subset of the packages.

**Comment by jack-oquin** [comment]
It took a little over an hour to build all the Kinetic repo packages on **bender**, which has an old Dell laptop.

**Comment by jack-oquin** [comment]
It turns out catkin build can use a metapackage as a whitelist, building only its dependencies (recursively). That way we can check out the whole repository, but only build segbot_v2 packages, or similarly for the other platforms.

**Comment by jack-oquin** [comment]
I divided the tests into two parts: **only_segbot_arm** and **only_segbot_base**. The segbot base test runs successfully, but the segbot arm test fails with a similar timeout after starting **segbot_arm_manipulation**.

See: https://travis-ci.org/utexas-bwi/segbot/jobs/337009286

**Comment by jack-oquin** [comment]
Commit e5d0a38 is an attempt to get the kinetic branch test to succeed by commenting out the segbot arm tests.

**Comment by jack-oquin** [comment]
That worked, but we still need to figure out what's wrong with the commented-out arm tests.

**Comment by jack-oquin** [comment]
@nickswalker: I'm going to leave the arm tests commented out for now. At least, the other packages can now get some CI testing. 

If you want to experiment with the arm tests, uncomment the [three lines here](https://github.com/utexas-bwi/segbot/blob/kinetic/.travis.yml#L15), and push to some experiemental branch. I've been using **travis-kinetic** for that, deleting it to avoid confusion, as it tends to diverge from the real **kinetic** branch.

Meanwhile, I'm going to work on creating a custom BWI package repository, so we don't normally need to build things like the segway drivers, kinova-ros, or agile_grasp. That may end up solving this issue, too.

**Comment by jack-oquin** [comment]
That last commit was supposed to run the arm tests, but not fail the whole job if they did not succeed. That didn't work.

**Comment by jack-oquin** [comment]
The original Travis config no longer works for Kinetic.
